variables:
  FF_POSIXLY_CORRECT_ESCAPES: "true"

stages:
  - build
  - test

build_project:
  stage: build
  script:
    - dotnet restore
    - dotnet build
  only:
    - merge_requests
    - branches
  tags:
    - runner-docker

unit_tests:
  stage: test
  script:
    - dotnet test
  only:
    - merge_requests
    - branches
  tags:
    - runner-docker
