
services:
  - docker:19.03.12-dind

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_TLS_CERTDIR: "/certs"
  FF_POSIXLY_CORRECT_ESCAPES: "true"


stages:
  - build
  - test
  - push

build_project:
  stage: build
  script:
    - dotnet restore
    - dotnet build
  only:
    - merge_requests
    - branches
  tags:
    - runner-docker

unit_tests:
  stage: test
  script:
    - dotnet test
  only:
    - merge_requests
    - branches
  tags:
    - runner-docker

build_and_push_to_registry:
  stage: push
  script:
    - docker login -u $AZURE_REGISTRY_USER -p $AZURE_REGISTRY_PASSWORD $AZURE_REGISTRY_SERVER
    - docker build -t $AZURE_REGISTRY_SERVER/freelancingplatform:latest .
    - docker push $AZURE_REGISTRY_SERVER/freelancingplatform:latest
  only:
    - master
  tags:
    - runner-docker
