version: '3.8'

services:
  web:
    image: registry.eimaen.pw/students-lab/freelancing-project
    networks:
      - caddy
    labels:
      caddy: 'students-lab.eimaen.pw'
      caddy.reverse_proxy: '{{upstreams 8080}}'
    environment:
      DOTNET_ENVIRONMENT: 'Production'
    volumes:
      - '/opt/students-lab/appsettings.json:/app/appsettings.Production.json'
    restart: unless-stopped

networks:
  caddy:
    external: true